apiVersion: v1
kind: Service
 
metadata:
  name: perf-publisher-service
  namespace: default
  labels:
    prom: goclient
 
spec:
  type: NodePort
  selector:
    app: perf-publisher
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
 
metadata:
  name: stream-publisher
  namespace: default
  labels:
    app: perf-publisher
 
spec:
  serviceName: "perf-publisher-service"
  replicas: 2
  selector:
    matchLabels:
      app: perf-publisher
  template:
    metadata:
      labels:
        app: perf-publisher
        prom: goclient
    spec:
      nodeSelector:
        PublisherKey: Server-1
      tolerations:
      - key: "PublisherTaint"
        operator: "Equal"
        value: "Non-Publisher"
        effect: "NoSchedule"
      containers:
      - name: go-buffer-publish
        image: natshelmacr.azurecr.io/go-buffer-publish:1.3.0
        ports:
          - containerPort: 3000
            name: web
        resources:
          requests:
            memory: "2Gi"
            cpu: "7000m"
        envFrom:
        - configMapRef:
            name: nats-db-st-config-map
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name